export const productColors = [
    { background: '#4285F4', text: 'white' },
    { background: '#34A853', text: 'white' },
    { background: '#FF9D00', text: 'black' },
    { background: '#FFC52F', text: 'black' },
    { background: '#B26E00', text: 'white' },
    { background: '#4285F4', text: 'white' },
    { background: '#34A853', text: 'white' },
    { background: '#FF9D00', text: 'black' },
    { background: '#FFC52F', text: 'black' },
    { background: '#B26E00', text: 'white' },
    { background: '#4285F4', text: 'white' },
    { background: '#34A853', text: 'white' },
    { background: '#FF9D00', text: 'black' },
    { background: '#FFC52F', text: 'black' },
    { background: '#B26E00', text: 'white' },
];
